version: '3'
services:
  web:
      build:
        context: .
        dockerfile: ../scripts/containers/nginx/Dockerfile
      volumes:
        - ../:/var/www/html
      ports:
          - "8080:80"
      depends_on:
          - php
  php:
      build:
        context: .
        dockerfile: ../scripts/containers/php/Dockerfile
      volumes:
        - ../:/var/www/html
